version: 2

sources:
  - name: caec_staging
    schema: caec_staging
    tables:
      - name: sessionized_events
        description: "Sessionized clickstream events loaded from PySpark job"
        freshness:
          warn_after: { count: 6, period: hour }
        loaded_at_field: event_time
