caec:
  target: dev
  outputs:
    dev:
      type: postgres
      host: caec_postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: dbt
      threads: 1
