name: 'caec'
version: '1.0'
config-version: 2

profile: 'caec_bigquery'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  caec:
    staging:
      +materialized: view
    marts:
      +materialized: table

