name: WIF sanity-check
on: { workflow_dispatch: {} }

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account:           "caec-ops-sa@eternal-channel-457606-h5.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Show active account
        run: gcloud auth list

      - name: List bucket
        run: gsutil ls -b gs://caec-scripts
